// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SVwCHiYT62cOPOTfEFBNrXPBpXM9PgY',
    appId: '1:568994211198:web:150dbbeef186defd37ff2f',
    messagingSenderId: '568994211198',
    projectId: 'gen-lang-client-0584808245',
    authDomain: 'gen-lang-client-0584808245.firebaseapp.com',
    storageBucket: 'gen-lang-client-0584808245.firebasestorage.app',
    measurementId: 'G-1GYM8WV9MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUtOqgI8hFbnEtVTq8Vr1xWWLTaYoNHpI',
    appId: '1:568994211198:android:42dc8bb01642d41b37ff2f',
    messagingSenderId: '568994211198',
    projectId: 'gen-lang-client-0584808245',
    storageBucket: 'gen-lang-client-0584808245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5YYXUf3g0MwMb0tfdzuoz111WgcIfDc',
    appId: '1:568994211198:ios:63267c8673dfef8237ff2f',
    messagingSenderId: '568994211198',
    projectId: 'gen-lang-client-0584808245',
    storageBucket: 'gen-lang-client-0584808245.firebasestorage.app',
    iosBundleId: 'com.dukanest.dukanestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd5YYXUf3g0MwMb0tfdzuoz111WgcIfDc',
    appId: '1:568994211198:ios:63267c8673dfef8237ff2f',
    messagingSenderId: '568994211198',
    projectId: 'gen-lang-client-0584808245',
    storageBucket: 'gen-lang-client-0584808245.firebasestorage.app',
    iosBundleId: 'com.dukanest.dukanestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-SVwCHiYT62cOPOTfEFBNrXPBpXM9PgY',
    appId: '1:568994211198:web:df27ef4e206748a237ff2f',
    messagingSenderId: '568994211198',
    projectId: 'gen-lang-client-0584808245',
    authDomain: 'gen-lang-client-0584808245.firebaseapp.com',
    storageBucket: 'gen-lang-client-0584808245.firebasestorage.app',
    measurementId: 'G-CP6MK5RVHJ',
  );
}
